[all:vars]
ansible_user=student

[dns]
servera ansible_host=172.25.250.10

[automount]
servera

[logkeeper]
servera

[email]
servera

[www]
servera

[wiki]
servera

[database]
serverb ansible_host=172.25.250.11

[storage]
serverb

[webservices:children]
www
wiki

[webservers:children]
database
webservices
