[all:vars]
ansible_user=student
ansible_ssh_password=student

[dns]
servera ansible_host=172.25.250.10

[logs]
servera

[mail]
servera

[www]
servera

[wiki]
servera

[db]
serverb ansible_host=172.25.250.11

[storage]
serverb
