---
- hosts: localhost
  connection: local
  roles:
  - role: testbench # Necessary to generate SSH keys for security role

- hosts: all
  roles:
  - role: cleanup # Only necessary because of the super weird RedHat lab configuration
  - role: users
  - role: security
  - role: dns
  become: yes

- hosts: all
  roles:
  - role: storage
  become: yes

- hosts: automount
  roles:
  - role: automount
  become: yes

- hosts: database
  roles:
  - role: database
  become: yes

#- hosts: wiki
#  roles:
#  - role: wiki
#  become: yes

#- hosts: www
#  roles:
#  - role: www
#  become: yes

#- hosts: email
#  roles:
#  - role: email
#  become: yes

- hosts: all
  roles:
  - role: logging
  - role: patching
  become: yes

- hosts: all
  roles:
  - role: verification
