---
- name: Create primary groups
  ansible.builtin.group:
    name: "{{ item.username }}"
    state: present
  register: primary_report
  loop: "{{ users }}"

- name: Create secondary groups
  ansible.builtin.group:
    name: "{{ item }}"
    state: present
  register: secondary_report
  loop: >-
    {{
       users
       | selectattr('groups', 'defined')
       | map(attribute='groups')
       | flatten
       | unique
       | list
    }}

- name: Get created groups
  ansible.builtin.set_fact:
    created_groups: >-
      {{
        (
          primary_report.results
          | selectattr('changed', 'equalto', true)
          | map(attribute='item')
          | list
        )
        +
        (
          secondary_report.results
          | selectattr('changed', 'equalto', true)
          | map(attribute='item')
          | list
        )
      }}

- name: Accumulate created groups into report
  ansible.builtin.set_fact:
    run_report: >-
      {{
        run_report | default({}) |
        combine(
          {
            'groups': {
              'created': created_groups,
              'count': created_groups | length
            }
          },
          recursive=True
        )
      }}
  when: created_groups | length > 0
