---
- name: Install Postfix and mail utilities
  ansible.builtin.package:
    name:
    - postfix
    - s-nail
    state: present

- name: Ensure postfix is enabled
  ansible.builtin.service:
    name: postfix
    enabled: true
    state: started

- name: Configure Postfix
  ansible.builtin.include_tasks: mail_server.yml
  when: "'email' in group_names"
