---
- name: Configure NFS server
  ansible.builtin.include_tasks: nfs_server.yml
  when: "'storage' in group_names"

- name: Configure NFS clients
  ansible.builtin.include_tasks: nfs_client.yml
  when: "'storage' not in group_names"
