---
- name: Install NFS utilities
  ansible.builtin.include_tasks: nfs_utils.yml

- name: Ensure NFS service enabled
  ansible.builtin.service:
    name: nfs-server
    state: started
    enabled: true

- name: Setup LVM
  ansible.builtin.include_role:
    name: lvm
  vars:
    vg_name: "{{ storage_vg }}"
    lv_name: "{{ storage_lv }}"
    dev_list: "{{ storage_dev_list }}"
    mount_path: "{{ shared_mount }}"
    mount_group: "{{ storage_group }}"
    create_mount_point: true

- name: Configure export
  ansible.builtin.lineinfile:
    path: "{{ exports_path }}"
    line: "{{ shared_mount }} {{ network_mask }}(rw,sync)"
    create: yes
    owner: root
    group: root
    mode: '0644'
  register: export_report

- name: Ensure proper setup
  block:
  - name: Ensure SELinux context
    ansible.builtin.file:
      path: "{{ exports_path }}"
      setype: etc_t

  - name: Restart NFS
    ansible.builtin.service:
      name: nfs-server
      state: restarted
  when: export_report.changed | default(false)

- name: Open DNS ports
  ansible.posix.firewalld:
    service: "{{ item }}"
    permanent: true
    state: enabled
    immediate: true
  loop: "{{ storage_services }}"

- name: Create directory for per-user directories
  ansible.builtin.file:
    path: "{{ shared_mount }}/users"
    state: directory
    owner: root
    group: "{{ storage_group }}"
    mode: '2770'    

- name: Create per-user NFS directories
  ansible.builtin.file:
    path: "{{ shared_mount }}/users/{{ item.username }}"
    state: directory
    owner: "{{ item.username }}"
    group: "{{ item.username }}"
    mode: '0750'
  loop: "{{ users }}"
  when: storage_group in item.groups | default([])
